=== LucaMannella/DP2_Assignment1_2015/dtd/wfInfo.dtd
<!-- DTD for a Workflow Management System -->
<!ELEMENT WorkflowManager (workflow | process)+ >

<!ELEMENT workflow (action+) >
<!ATTLIST workflow
	name ID #REQUIRED	>
	
<!ELEMENT action (simple_action | process_action) >
<!ATTLIST action
	id ID #REQUIRED
	name CDATA #REQUIRED
	role CDATA #REQUIRED	>
	
<!ELEMENT simple_action EMPTY >
<!ATTLIST simple_action
	nextActions	IDREFS #IMPLIED	>

<!ELEMENT process_action EMPTY >
<!ATTLIST process_action
	nextProcess IDREF #REQUIRED >

<!ELEMENT process (action_status)+ >
<!ATTLIST process
	code ID #REQUIRED
	workflow IDREF #REQUIRED	>


<!-- Do we have to put some information related to the automatic instantiation? -->
<!-- how manage action and actor? -->
<!ELEMENT action_status EMPTY>
<!ATTLIST action_status		
	actor IDREF "NULL"
	timestamp CDATA "Not Finished"	>

<!ELEMENT actor EMPTY >
<!ATTLIST actor
	name ID #REQUIRED
	role CDATA #REQUIRED	>

<!-- 
	We can manage the problem in 2 differente ways: 
	using the IDRef(s) like in this case or doesn't use them.
	In the first case we introduce the problem of the managing of the IDs;
	in the second case we have to manage the "pointer" directly inside the application code.
-->

<!-- This DTD file was developed by Luca Mannella for the Assignment 1
	 of the course Distributed Programming II in Politechnic University of Turin. -->

=== LucaMannella/DP2_Assignment1_2015/dtd/wfInfo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE WorkflowManager SYSTEM "wfInfo.dtd" >

<WorkflowManager>

	<workflow name="ArticleProduction">
		<action id="ArticleProduction_Writing" name="Writing" role="Journalist">
			<simple_action nextActions="ArticleProduction_Checking"></simple_action>
		</action>
		<action id="ArticleProduction_Checking" name="Checking" role="Editor">
			<simple_action nextActions="ArticleProduction_Revising ArticleProduction_Publication"></simple_action>
		</action>
		<action id="ArticleProduction_Revising" name="Revising" role="Journalist">
			<simple_action nextActions="ArticleProduction_Checking"></simple_action>
		</action>
		<action id="ArticleProduction_Publication" name="Publication" role="Editor">
			<simple_action></simple_action>
		</action>
	</workflow>
	
	<workflow name="SaleManagement">
		<action id="SaleManagement_AcceptOrder" name="AcceptOrder" role="Salesman">
			<simple_action nextActions="SaleManagement_NormalSale SaleManagement_PrepaidSale"></simple_action>
		</action>
		<action id="SaleManagement_NormalSale" name="NormalSale" role="SalesManager">
			<process_action nextProcess="NormalSale"></process_action>
		</action>
		<action id="SaleManagement_PrepaidSale" name="PrepaidSale" role="SalesManager">
			<process_action nextProcess="PrepaidSale"></process_action>
		</action>
	</workflow>
	
	<workflow name="NormalSale">
		<action id="NormalSale_GoodsDelivery" name="GoodsDelivery" role="Warehouseman">
			<simple_action></simple_action>
		</action>
		<action id="NormalSale_InvoiceIssuance" name="InvoiceIssuance" role="Accountingman">
			<simple_action nextActions="NormalSale_PaymentRec"></simple_action>
		</action>
		<action id="NormalSale_PaymentRec" name="PaymentRec" role="Accountingman">
			<simple_action></simple_action>
		</action>
	</workflow>
	
	<workflow name="PrepaidSale">
		<action id="PrepaidSale_InvoiceIssuance" name="InvoiceIssuance" role="Accountingman">
			<simple_action nextActions="PrepaidSale_PaymentRec"></simple_action>
		</action>
		<action id="PrepaidSale_PaymentRec" name="PaymentRec" role="Accountingman">
			<simple_action nextActions="PrepaidSale_GoodsDelivery"></simple_action>
		</action>
		<action id="PrepaidSale_GoodsDelivery" name="GoodsDelivery" role="Warehouseman">
			<simple_action></simple_action>
		</action>
	</workflow>
	
</WorkflowManager>

<!-- This XML file was developed by Luca Mannella for the Assignment 1
	 of the course Distributed Programming II in Politechnic University of Turin. -->
